<h1 style = "color : Brown">NumPy</h1>

- __NumPy__ is a Python library.
- It is used for working with arrays.
- It is short for "Numerical Python".
- It is used for computation and processing of single and multi dimensional array of elements.
- Smaller memory consumption and better runtime behavior.

In [ ]:
# To install the library

pip install numpy

import numpy

## Basic Operations

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
type(a)

numpy.ndarray

In [5]:
a = np.array([1,2,3], dtype = float)
print(a)

[1. 2. 3.]


In [6]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
type(b)

numpy.ndarray